.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. deimos_qt test_deimos_qt
clean: FORCE
	$(MAKE) -C .. deimos_qt_clean test_deimos_qt_clean
check: FORCE
	$(MAKE) -C .. test_deimos_qt_check
deimos-qt deimos-qt.exe: FORCE
	 $(MAKE) -C .. deimos_qt
